import { Page, Locator, expect } from '@playwright/test';
import type { Locale } from '../config';

/**
 * A single fillable control discovered inside a form.
 */
export interface Field {
  locator: Locator;
  tag: 'input' | 'select' | 'textarea';
  type: string;          // input @type, '' for select/textarea
  name: string;
  id: string;
  placeholder: string;
  ariaLabel: string;
  required: boolean;
  autocomplete: string;
}

/** All searchable text hints for a field, lowercased. */
function hints(f: Field): string {
  return [f.name, f.id, f.placeholder, f.ariaLabel, f.autocomplete]
    .join(' ')
    .toLowerCase();
}

const matches = (h: string, ...words: string[]) => words.some((w) => h.includes(w));

/**
 * Locale-appropriate sample data. Kept deliberately identifiable so real
 * submissions (if SUBMIT_FOR_REAL is ever used) are obviously test traffic.
 */
function sampleData(loc: Locale) {
  const phones: Record<string, string> = {
    'en-US': '+1 212 555 0142',
    'en-CA': '+1 416 555 0142',
    'fr-CA': '+1 514 555 0142',
    'en-GB': '+44 20 7946 0958',
    'de-DE': '+49 30 901820',
    'fr-FR': '+33 1 70 18 99 00',
    'es-ES': '+34 91 123 45 67',
  };
  const postals: Record<string, string> = {
    'en-US': '10001',
    'en-CA': 'M5V 2T6',
    'fr-CA': 'H3B 4W8',
    'en-GB': 'EC1A 1BB',
    'de-DE': '10115',
    'fr-FR': '75001',
    'es-ES': '28001',
  };
  return {
    first: 'QA',
    last: 'Automation',
    fullName: 'QA Automation',
    email: 'qa.automation.test@example.com',
    phone: phones[loc.lang] ?? '+1 212 555 0142',
    company: 'DAC QA Automation (test)',
    jobTitle: 'Test Engineer',
    website: 'https://example.com',
    postal: postals[loc.lang] ?? '10001',
    number: '42',
    date: '2030-01-01',
    password: 'TestPass123!',
    message:
      'This is an automated QA test submission — please disregard. ' +
      'Generated by the Playwright form-testing suite.',
    generic: 'QA Test Value',
  };
}

/**
 * Compute a plausible VALID value for a field from its type + text hints.
 * Returns null for controls we handle separately (checkbox/radio/select/file/hidden).
 */
export function validValue(f: Field, loc: Locale): string | null {
  const d = sampleData(loc);
  const h = hints(f);

  if (['hidden', 'submit', 'button', 'reset', 'image', 'file'].includes(f.type)) return null;
  if (f.type === 'checkbox' || f.type === 'radio') return null;

  // Type-driven first — most reliable signal.
  switch (f.type) {
    case 'email':
      return d.email;
    case 'tel':
      return d.phone;
    case 'url':
      return d.website;
    case 'number':
    case 'range':
      return d.number;
    case 'date':
      return d.date;
    case 'password':
      return d.password;
  }

  // Name/label-driven for generic text inputs + textareas.
  if (matches(h, 'email', 'e-mail', 'correo', 'courriel')) return d.email;
  if (matches(h, 'phone', 'tel', 'mobile', 'telefon', 'téléphone', 'teléfono')) return d.phone;
  if (matches(h, 'first', 'prenom', 'prénom', 'vorname', 'nombre')) return d.first;
  if (matches(h, 'last', 'surname', 'nom', 'nachname', 'apellido')) return d.last;
  if (matches(h, 'name', 'fullname', 'your-name')) return d.fullName;
  if (matches(h, 'company', 'organis', 'organiz', 'unternehmen', 'entreprise', 'empresa'))
    return d.company;
  if (matches(h, 'title', 'role', 'position', 'puesto', 'poste')) return d.jobTitle;
  if (matches(h, 'website', 'url', 'site')) return d.website;
  if (matches(h, 'zip', 'postal', 'plz', 'code postal', 'código postal')) return d.postal;
  if (matches(h, 'message', 'comment', 'inquir', 'enquir', 'details', 'mensaje', 'nachricht'))
    return d.message;
  if (f.tag === 'textarea') return d.message;

  return d.generic;
}

/**
 * Discover every fillable control inside a form Locator.
 */
export async function discoverFields(form: Locator): Promise<Field[]> {
  const handles = await form.locator('input, select, textarea').all();
  const fields: Field[] = [];
  for (const locator of handles) {
    const [tag, type, name, id, placeholder, ariaLabel, required, autocomplete] =
      await locator.evaluate((el) => [
        el.tagName.toLowerCase(),
        el.getAttribute('type') || '',
        el.getAttribute('name') || '',
        el.getAttribute('id') || '',
        el.getAttribute('placeholder') || '',
        el.getAttribute('aria-label') || '',
        el.hasAttribute('required') || el.getAttribute('aria-required') === 'true',
        el.getAttribute('autocomplete') || '',
      ] as const);
    fields.push({
      locator,
      tag: tag as Field['tag'],
      type,
      name,
      id,
      placeholder,
      ariaLabel,
      required,
      autocomplete,
    });
  }
  return fields;
}

/** Only fields a user could actually interact with. */
async function isFillable(f: Field): Promise<boolean> {
  if (['hidden', 'submit', 'button', 'reset', 'image'].includes(f.type)) return false;
  try {
    return await f.locator.isVisible();
  } catch {
    return false;
  }
}

/**
 * Fill every control in the form with VALID data.
 * Handles text/select/checkbox/radio; skips hidden + file inputs.
 */
export async function fillValid(fields: Field[], loc: Locale): Promise<number> {
  let filled = 0;
  const seenRadioGroups = new Set<string>();

  for (const f of fields) {
    if (!(await isFillable(f))) continue;

    if (f.type === 'checkbox') {
      // Consent/opt-in boxes are usually required to submit.
      try {
        await f.locator.check({ timeout: 5000 });
        filled++;
      } catch { /* non-interactable checkbox */ }
      continue;
    }

    if (f.type === 'radio') {
      if (seenRadioGroups.has(f.name)) continue;
      seenRadioGroups.add(f.name);
      try {
        await f.locator.check({ timeout: 5000 });
        filled++;
      } catch { /* ignore */ }
      continue;
    }

    if (f.tag === 'select') {
      try {
        // Pick the first non-empty option value.
        const value = await f.locator.evaluate((el: HTMLSelectElement) => {
          const opt = Array.from(el.options).find((o) => o.value && !o.disabled);
          return opt ? opt.value : '';
        });
        if (value) {
          await f.locator.selectOption(value);
          filled++;
        }
      } catch { /* ignore */ }
      continue;
    }

    const value = validValue(f, loc);
    if (value == null) continue;
    try {
      await f.locator.fill(value, { timeout: 5000 });
      filled++;
    } catch { /* readonly / non-interactable */ }
  }
  return filled;
}

/**
 * Prepare the form for an INVALID submission: clear required text fields and put a
 * malformed value in any email field. Leaves the form failing client-side validation.
 */
export async function fillInvalid(fields: Field[]): Promise<void> {
  for (const f of fields) {
    if (!(await isFillable(f))) continue;
    if (['checkbox', 'radio', 'file'].includes(f.type) || f.tag === 'select') continue;

    const h = hints(f);
    try {
      if (f.type === 'email' || matches(h, 'email', 'e-mail', 'correo', 'courriel')) {
        // Present but malformed — should trip format validation, not just "required".
        await f.locator.fill('not-an-email', { timeout: 5000 });
      } else {
        await f.locator.fill('', { timeout: 5000 });
      }
    } catch { /* ignore */ }
  }
}

/** Find the most likely submit control within the form. */
export function submitButton(form: Locator): Locator {
  return form
    .locator(
      'button[type=submit], input[type=submit], button:not([type=button]):not([type=reset])',
    )
    .first();
}

/**
 * Click submit and observe what the browser did.
 *
 * In dry-run, any POST/XHR the submit triggers is intercepted and answered with a
 * synthetic 200 — we record that a submission WAS attempted without delivering it.
 * Returns whether a submission request fired.
 */
export async function submitAndObserve(
  page: Page,
  form: Locator,
  { dryRun }: { dryRun: boolean },
): Promise<{ requestFired: boolean; navigated: boolean }> {
  let requestFired = false;
  const startUrl = page.url();

  // Resolve the form's own action so we only treat THE FORM's submission as "fired" —
  // not unrelated analytics/marketing beacons that also POST on the page.
  const formAction = await form
    .evaluate((f: HTMLFormElement) => f.action || '')
    .catch(() => '');
  let actionPath = '';
  try {
    if (formAction) actionPath = new URL(formAction).pathname;
  } catch { /* relative/empty action */ }

  // Endpoints commonly used by WordPress/CF7/HubSpot/Gravity form submissions.
  const FORM_ENDPOINT_RE =
    /(wp-json.*(contact-form-7|cf7|gravityforms|feedback)|wp-admin\/admin-ajax\.php|wpcf7|hsforms\.com|hubspot|forms\.hubspot|\/gravityforms\/|formstack|marketo)/i;

  /** Does this request look like the form we're testing submitting itself? */
  const isFormSubmission = (req: import('@playwright/test').Request): boolean => {
    const method = req.method();
    if (method === 'GET' || method === 'HEAD') return false;
    const url = req.url();
    if (actionPath && url.includes(actionPath)) return true;
    return FORM_ENDPOINT_RE.test(url);
  };

  const routeHandler = async (route: import('@playwright/test').Route) => {
    const req = route.request();
    if (isFormSubmission(req)) {
      requestFired = true;
      if (dryRun) {
        // Synthetic success so the app's UI can proceed WITHOUT delivering a real lead.
        await route.fulfill({
          status: 200,
          contentType: 'application/json',
          body: JSON.stringify({ status: 'mail_sent', message: 'DRY_RUN intercepted' }),
        });
        return;
      }
    }
    await route.continue();
  };

  if (dryRun) await page.route('**/*', routeHandler);

  try {
    const btn = submitButton(form);
    await btn.scrollIntoViewIfNeeded().catch(() => {});
    // Watch specifically for the form's own submission request (not any POST).
    const reqPromise = page
      .waitForRequest((r) => isFormSubmission(r), { timeout: 8000 })
      .then(() => { requestFired = true; })
      .catch(() => {});

    await btn.click({ timeout: 10000 }).catch(() => {});
    await reqPromise;
    await page.waitForTimeout(1500); // let client-side UI settle
  } finally {
    if (dryRun) await page.unroute('**/*', routeHandler).catch(() => {});
  }

  const navigated = page.url() !== startUrl;
  return { requestFired, navigated };
}

/**
 * Heuristic: did visible client-side validation errors appear?
 * Covers native :invalid, common error classes, and aria-invalid.
 */
export async function hasValidationErrors(form: Locator): Promise<boolean> {
  return form.evaluate((f: HTMLFormElement) => {
    // Native constraint validation.
    const controls = Array.from(f.querySelectorAll('input, select, textarea')) as (
      | HTMLInputElement
      | HTMLSelectElement
      | HTMLTextAreaElement
    )[];
    const nativeInvalid = controls.some(
      (c) => typeof c.checkValidity === 'function' && !c.checkValidity(),
    );
    if (nativeInvalid) return true;

    // Framework/library error markers.
    const errorSelectors = [
      '[aria-invalid="true"]',
      '.error:not(:empty)',
      '.is-invalid',
      '.wpcf7-not-valid-tip',
      '.hs-error-msg',
      '.field-error',
      '.invalid-feedback',
      '[class*="error"]:not(:empty)',
    ];
    for (const sel of errorSelectors) {
      const el = f.querySelector(sel);
      if (el && (el as HTMLElement).offsetParent !== null) return true;
    }
    return false;
  });
}

/**
 * Heuristic success signal after a valid submission: a thank-you/confirmation
 * message, a success class, or the form no longer being present.
 */
export async function looksSuccessful(page: Page, form: Locator): Promise<boolean> {
  // Form removed/replaced is a common success pattern.
  const formGone = (await form.count()) === 0 || !(await form.isVisible().catch(() => false));

  const successText = await page
    .locator(
      'text=/thank you|thanks|success|received|we.ll be in touch|merci|danke|gracias|message sent/i',
    )
    .first()
    .isVisible()
    .catch(() => false);

  const successClass = await page
    .locator('.wpcf7-mail-sent-ok, .hs-form-success, .form-success, .success-message')
    .first()
    .isVisible()
    .catch(() => false);

  return formGone || successText || successClass;
}
